[tool.poetry]
name = "pasim"
version = "0.1.0"
description = "A scientific simulation framework."
authors = ["Your Name <your@email.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
numpy = "*"
networkx = "*"
pydantic = "*"
pyyaml = "*"

[tool.poetry.scripts]
pasim = "pasim.cli:main"

[tool.poetry.group.dev.dependencies]
pytest = "*"
mypy = "*"
ruff = "*"
types-networkx = "*"
types-pyyaml = "*"
pre-commit = "^4.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 140
preview = true

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"
